### PR TITLE
update viewer to 2.7.2

### PR DESCRIPTION
**Pull request by toloudis**
This introduces several new 3d viewer features into CFE.

In particular:
1. The "info panel" now arrives.  All measured feature values are propagated from CFE into a displayable panel in the 3d viewer, along with some general metadata like image dimensions.
2. 2D modes now default to "middle slice" instead of single slice, and they render at higher quality than previously.
3. if the images are provided as Zarr, then the viewer attempts to display a higher resolution in XY slice mode.  This can result in slower performance but greater image quality and detail.  This mode will receive several optimizations in coming weeks/months.

### CODE REVIEW

**Review by meganrm — APPROVED** [review]

**Comment by toloudis** [comment]
@meganrm Thanks for the screenshot- I am not seeing that.  What browser and platform?  And did you do a build with node 16? from scratch?

**Comment by meganrm** [comment]
> @meganrm Thanks for the screenshot- I am not seeing that. What browser and platform? And did you do a build with node 16? from scratch?

Yes it was a fresh build, node 18. I see it on the built website 3d viewer too. I'm in safari

**Comment by meganrm** [comment]
> > @meganrm Thanks for the screenshot- I am not seeing that. What browser and platform? And did you do a build with node 16? from scratch?
> 
> Yes it was a fresh build, node 18. I see it on the built website 3d viewer too. I'm in safari

It seems to be a safari issue. It's normal in chrome

**Comment by toloudis** [comment]
https://github.com/allen-cell-animated/website-3d-cell-viewer/issues/176

**Comment by toloudis** [comment]
I'll run it once although in practice it never fixes everything.

**Pull request merged**
